version: '3'

services:
  database:
    container_name: d_data
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD : <password>
    networks:
      - draw
    # volumes:
    #   - <datapath>:/var/lib/mysql #Zorunlu degil datalarınızı localinizden kaydetmek isterseniz ekleyebilirisniz
      
  
  drawgeo:
    container_name: d_geo
    image: mzahidberber/drawgeo:latest
    restart: always
    command: python manage.py runserver 0.0.0.0:5001
    environment:
      - SECRET_KEY='djang12312o-insecure-h@&*123kas123dasdibx-123s=pa^+l=3asduzfe6mpuuo9(em(f&uv9xzveazwz4'
      - cors=* # http://127.0.0.1:50;http://127.0.0.1:51 gibi ';' ile cors yetkisi verilecek url eklenebilir * her istegi kabul etmesi içindir
      # - ALLOWED_HOSTS=<ip> #Zorunlu degil local haricinde bir yerde çalıştırılırsa ip numarası eklenmeli
      # - DEBUG=False #Zorunlu degil varsayılan olarak False
    ports:
      - '5001:5001'
    networks:
      - draw

  drawapi:
    container_name: d_api
    image: mzahidberber/drawapi:latest
    restart: always
    ports:
      - '5000:80'
    environment:
      - geoUrl=http://drawgeo:5001/
      - dbHost=database
      - dbPort=3306
      - dbName=drawdb
      - dbPassword=<password>
      - cors=* # http://127.0.0.1:50;http://127.0.0.1:51 gibi ';' ile cors yetkisi verilecek url eklenebilir * her istegi kabul etmesi içindir
      # - exeVersion=1.0.1 #Zorunlu degil clientin exe versionunu kontrolu için veriliyor
    networks:
      - draw

  drawauth:
    container_name: d_auth
    image: mzahidberber/drawauth:latest
    restart: always
    ports:
      - '5002:80'
    environment:
      - dbHost=database
      - dbPort=3306
      - dbName=drawdb
      - dbPassword=<password>
      - cors=* # http://127.0.0.1:50;http://127.0.0.1:51 gibi ';' ile cors yetkisi verilecek url eklenebilir * her istegi kabul etmesi içindir
    networks:
      - draw

networks:
  draw:
    driver: bridge
