# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\QtDesignerUI\LayerBoxUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LayerBox(object):
    def setupUi(self, LayerBox):
        LayerBox.setObjectName("LayerBox")
        LayerBox.resize(700, 300)
        LayerBox.setSizeGripEnabled(False)
        LayerBox.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(LayerBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AddLayer = QtWidgets.QPushButton(LayerBox)
        self.AddLayer.setObjectName("AddLayer")
        self.horizontalLayout_2.addWidget(self.AddLayer)
        self.RemoveLayer = QtWidgets.QPushButton(LayerBox)
        self.RemoveLayer.setObjectName("RemoveLayer")
        self.horizontalLayout_2.addWidget(self.RemoveLayer)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.LayerList = QtWidgets.QTableWidget(LayerBox)
        self.LayerList.setAutoScrollMargin(16)
        self.LayerList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.LayerList.setAlternatingRowColors(False)
        self.LayerList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.LayerList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.LayerList.setTextElideMode(QtCore.Qt.ElideRight)
        self.LayerList.setShowGrid(True)
        self.LayerList.setGridStyle(QtCore.Qt.DashLine)
        self.LayerList.setWordWrap(True)
        self.LayerList.setCornerButtonEnabled(True)
        self.LayerList.setRowCount(0)
        self.LayerList.setColumnCount(7)
        self.LayerList.setObjectName("LayerList")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.LayerList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LayerList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.LayerList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.LayerList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.LayerList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.LayerList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.LayerList.setHorizontalHeaderItem(6, item)
        self.LayerList.horizontalHeader().setVisible(True)
        self.LayerList.horizontalHeader().setCascadingSectionResizes(False)
        self.LayerList.horizontalHeader().setHighlightSections(False)
        self.LayerList.horizontalHeader().setSortIndicatorShown(True)
        self.LayerList.horizontalHeader().setStretchLastSection(False)
        self.LayerList.verticalHeader().setVisible(True)
        self.LayerList.verticalHeader().setCascadingSectionResizes(False)
        self.LayerList.verticalHeader().setDefaultSectionSize(20)
        self.LayerList.verticalHeader().setHighlightSections(False)
        self.LayerList.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout.addWidget(self.LayerList)

        self.retranslateUi(LayerBox)
        QtCore.QMetaObject.connectSlotsByName(LayerBox)

    def retranslateUi(self, LayerBox):
        _translate = QtCore.QCoreApplication.translate
        LayerBox.setWindowTitle(_translate("LayerBox", "Edit Layer"))
        self.AddLayer.setText(_translate("LayerBox", "Add"))
        self.RemoveLayer.setText(_translate("LayerBox", "Remove"))
        self.LayerList.setSortingEnabled(True)
        item = self.LayerList.horizontalHeaderItem(0)
        item.setText(_translate("LayerBox", "Name"))
        item = self.LayerList.horizontalHeaderItem(1)
        item.setText(_translate("LayerBox", "Lock"))
        item = self.LayerList.horizontalHeaderItem(2)
        item.setText(_translate("LayerBox", "Visibility"))
        item = self.LayerList.horizontalHeaderItem(3)
        item.setText(_translate("LayerBox", "Thickness"))
        item = self.LayerList.horizontalHeaderItem(4)
        item.setText(_translate("LayerBox", "Color"))
        item = self.LayerList.horizontalHeaderItem(5)
        item.setText(_translate("LayerBox", "Type"))
        item = self.LayerList.horizontalHeaderItem(6)
        item.setText(_translate("LayerBox", "Elements "))
